/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App greetMe = new App();
        assertNotNull("app should have a greeting", greetMe.getGreeting());
    }

    @Test public void testAppLinterCheck(){
        App linterTest = new App();

        assertEquals("Expected empty string", "", linterTest.linter("src/main/resources/noErrors.js"));
        assertEquals("One error expected", "Line 13: Missing a semicolon.", linterTest.linter("src/main/resources/oneError.js"));
        assertEquals("Three errors expected", "Line 3: Missing a semicolon.\n" +
                "Line 11: Missing a semicolon.\n" +
                "Line 15: Missing a semicolon.", linterTest.linter("src/main/resources/fewErrors.js"));
        assertEquals("Seven errors expected", "Line 3: Missing a semicolon.\n" +
                "Line 5: Missing a semicolon.\n" +
                "Line 6: Missing a semicolon.\n" +
                "Line 7: Missing a semicolon.\n" +
                "Line 8: Missing a semicolon.\n" +
                "Line 9: Missing a semicolon.\n" +
                "Line 15: Missing a semicolon.", linterTest.linter("src/main/resources/manyErrors.js"));
        assertEquals("Expected empty string", "", linterTest.linter("src/main/resources/empty.js"));
    }
}
