/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(linter("src/main/resources/gates.js"));
    }

    public static String linter(String path){

        Scanner jsScript = null;
        try{
            jsScript = new Scanner(new File(path));
        } catch (FileNotFoundException exception){
            System.out.println("No file found");
        }

        String errors = "";
        int lineCounter = 0;
        while(jsScript.hasNext()) {
            lineCounter++;
            String nextLine = jsScript.nextLine();
            if(nextLine.length() == 0) {
                continue;
            }

            if(nextLine.substring(nextLine.length() - 1).equals("{") || nextLine.substring(nextLine.length() - 1).equals("}")){
                continue;
            }

            if(nextLine.contains("if") || nextLine.contains("else")) {
                continue;
            }

            if(nextLine.substring(nextLine.length() - 1).equals(";")){
                continue;
            } else {
                if(errors.length() != 0){
                    errors += "\n";
                }
                errors += "Line " + lineCounter + ": Missing a semicolon.";
            }
        }

        return errors;
    }
}
