/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.junit.Assert.*;

public class LibraryTest {
//    @Test public void testRoll() {
//        Library classUnderTest = new Library();
////        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//        classUnderTest.roll(5);
////        assertArrayEquals(numb);
//    }

    @Test
    public void testRoll() {
        Library rolling = new Library();

        for(int i = 0; i < 10; i++){
            assertTrue("Array of rolls is the correct length", i == rolling.roll(i).length);
        }
    }

    @Test public void testContainsDuplicates() {
        Library containsDupes = new Library();
        assertTrue("Test of array that contains duplicates", containsDupes.containsDuplicates(new int[]{1, 2, 1}));
        assertFalse("Test of array with no duplicates", containsDupes.containsDuplicates(new int[]{1, 2, 8}));
    }

    @Test public void testFindAverage() {
        Library calculateAvg = new Library();
        assertEquals(3.0, calculateAvg.findAverage(new int[]{2,3,4}), 0);
        assertEquals(2.5, calculateAvg.findAverage(new int[]{1,2,3,4}), 0);
    }

    @Test public void testGetLowestOfAvgArr(){
        Library findLowestArr = new Library();
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        for(int[] integerArray : weeklyMonthTemperatures){
            System.out.println(findLowestArr.findAverage(integerArray));
        }
        assertArrayEquals(weeklyMonthTemperatures[2], findLowestArr.getLowestOfAveragesArray(weeklyMonthTemperatures));
    }
}
//Guidance from Bade
//    Bade (TA)
//1. Initialize the array
//
//        int[] numbers = new int[5];
//
//        ^^^ Always have to define the number of indices (spaces in the array) with Java ^^^
//
//        ____________________
//        2. Iterate through the array
//
//        for (int i = 0; i < numbers.length; i++) {
//        // all of our code here
//        }
//
//        _____________________
//        3. Fill each index of the array
//
//        You have an array of integers
//        index		elements
//        [0] 	= 	1
//        [1] 	= 	4
//        [2] 	= 	7
//        [3] 	= 	10
//
//        for (int i = 0; i < numbers.length; i++) {
//        //whatever calculation
//        you want
//        numbers[i] = //whatever number needs to be assigned
//
//        }