/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.junit.Assert.*;

public class LibraryTest {
//    @Test public void testRoll() {
//        Library classUnderTest = new Library();
////        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//        classUnderTest.roll(5);
////        assertArrayEquals(numb);
//    }

    @Test
    public void testRoll() {
        Library rolling = new Library();
        int[] output = rolling.roll(10000);
        int ones = 0;
        for(int i = 0; i < output.length; i++){
            if(output [i] == 1){
                ones++;
            }
        }
        assertTrue("there should be at least one 1", ones > 0);
        assertEquals("The length should be 10000", 10000, output.length);
    }

    @Test public void testContainsDuplicates() {
        Library contDupe = new Library();
        assertTrue("this one does", contDupe.containsDuplicates(new int[]{1, 2, 1}));
    }

    @Test public void testAverageOfArrays() {
        Library averages = new Library();
//        assertArrayEquals(new int[]{1,2,3}, averages.lowestOfAverages(new int[][]{{1, 2, 3}, {10, 20, 30}}));

    }







}
//Guidance from Bade
//    Bade (TA)
//1. Initialize the array
//
//        int[] numbers = new int[5];
//
//        ^^^ Always have to define the number of indices (spaces in the array) with Java ^^^
//
//        ____________________
//        2. Iterate through the array
//
//        for (int i = 0; i < numbers.length; i++) {
//        // all of our code here
//        }
//
//        _____________________
//        3. Fill each index of the array
//
//        You have an array of integers
//        index		elements
//        [0] 	= 	1
//        [1] 	= 	4
//        [2] 	= 	7
//        [3] 	= 	10
//
//        for (int i = 0; i < numbers.length; i++) {
//        //whatever calculation
//        you want
//        numbers[i] = //whatever number needs to be assigned
//
//        }