/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;


import java.util.Arrays;


public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

//    ================ Lab 2 'Roll' Revision Below =====================

    public int[] roll(int n){
        int[] diceArray = new int[n];
        for (int i = 0; i < n; i++){
            diceArray[i] = (int) Math.floor((Math.random() * 6) + 1);
        }
        System.out.println("Outcome of rolls" + Arrays.toString(diceArray));
        return diceArray;
    }

//    ================ Lab 2 'Contains Duplicates' Revision Below =====================

    public boolean containsDuplicates(int[] arrayToCheck){
        for(int slow = 0; slow < arrayToCheck.length; slow++){
            for(int fast = slow +1 ; fast < arrayToCheck.length; fast++){
                if(arrayToCheck[slow] == arrayToCheck[fast]){
                    System.out.println("Contains Duplicates!!");
                    return true;
                }
            }
        }
        System.out.println("No Duplicates Found.");
        return false;
    }

    //    ================ Lab 2 'Average' Revision Below =====================

    public double findAverage(int[] inputArray){
        double total = 0;
        for(int number : inputArray){
            total += number;
        }

        double output = total / inputArray.length;
        System.out.println("The average value is: " + output);
        return output;
    }


    public int[] getLowestOfAveragesArray(int[][] weeklyMonthTemperatures){
        double lowestAverage = findAverage(weeklyMonthTemperatures[0]);
        int[] outputArray = new int[0];

        for(int[] intArray : weeklyMonthTemperatures){
            double average = findAverage(intArray);
            boolean result = average < lowestAverage;
            if(result) {
                outputArray = intArray;
                lowestAverage = findAverage(intArray);
            }
        }
        System.out.println("Array with lowest average is: " + Arrays.toString(outputArray));
        return outputArray;
    }
}
